Messaging 3.1 - Javadoc
jakartaee/specifications pull request #464
Opened 2022-03-02 22:38 UTC by OndroMih

A separate PR with Javadoc files for #455

2022-05-03 16:23 UTC, jeanouii requested changes

2022-05-03 16:23 UTC, jeanouii commented on messaging/3.1/apidocs/allpackages-index.html
> +<div class="aboutLanguage"><br>Jakarta Messaging API v3.1.0-SNAPSHOT</div>
Looks like it's still using SNAPSHOT

2022-05-03 16:36 UTC, OndroMih commented on messaging/3.1/apidocs/allpackages-index.html
> +<div class="aboutLanguage"><br>Jakarta Messaging API v3.1.0-SNAPSHOT</div>
Fixed.

2022-05-12 16:05 UTC, jeanouii approved these changes

2022-05-12 16:05 UTC, merged