Zhoufang/master/1478
jakartaee/specifications pull request #499
Opened 2022-05-25 15:33 UTC by linkfang

For https://github.com/jakartaee/jakarta.ee/issues/1478

2022-05-31 21:51 UTC, linkfang commented
Got +1 from Kristy, https://github.com/jakartaee/jakarta.ee/issues/1478#issuecomment-1142628856

2022-06-02 06:50 UTC, ivargrimstad requested changes

2022-06-02 06:50 UTC, ivargrimstad commented on faces/_index.md
> +summary: "Jakarta Faces (JSF) defines an MVC framework for building user interfaces for web applications,
Remove "(JSF)"

2022-06-02 06:50 UTC, ivargrimstad commented on platform/10/_index.md
> +summary: "Jakarta EE Platform 10 defines a standard platform for hosting Jakarta EE (Java EE) applications. Find specifications and compatible implementations."
Remove (Java EE)

2022-06-02 06:50 UTC, ivargrimstad commented on platform/8/_index.md
> +summary: "Jakarta EE Platform 8 defines a standard platform for hosting Jakarta EE (Java EE) applications. Find specifications and compatible implementations."
Remove (Java EE)

2022-06-02 06:50 UTC, ivargrimstad commented on platform/9.1/_index.md
> +summary: "Jakarta EE Platform 9.1 defines a standard platform for hosting Jakarta EE (Java EE) applications. Find specifications and compatible implementations."
Remove (Java EE)

2022-06-02 06:50 UTC, ivargrimstad commented on platform/9/_index.md
> +summary: "Jakarta EE Platform 9 defines a standard platform for hosting Jakarta EE (Java EE) applications. Find specifications and compatible implementations."
Remove (Java EE)

2022-06-02 14:17 UTC, ivargrimstad approved these changes

2022-06-06 16:29 UTC, merged