WebSocket 2.2 plan update
jakartaee/specifications pull request #615
Opened 2023-05-23 09:27 UTC by markt-asf

## Plan Review PR template
When creating a specification project plan review, create PRs with the content defined as follows.

Include the following in the PR:
- [X] A directory in the form wombat/x.y where x.y is the release major.minor version.
- [X] An index page wombat/x.y/_index.md following [template](https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md)
- [X] Title should be on the form "Jakarta Wombat X.Y (under development)"
- [X] Includes a plan for the release. Usually, a couple of statements is enough. Otherwise, a link to a document describing the release.
- [X] Includes a detailed description of any backward incompatibility (Mark with **N/A** and check if none)
- [X] **N/A** Declares optional features if there are any (Mark with **N/A** and check if none)
- [X] Includes minimum Java SE version
- [X] **N/A** Describe any updates or required changes including splitting out the TCK (Mark with **N/A** and check if not planned)
- [X] Link to updated release record

2023-06-16 11:20 UTC, kazumura requested changes

2023-06-16 11:20 UTC, kazumura commented on websocket/2.2/_index.md
> +
Please add here
``` # Details```

2023-06-16 11:52 UTC, markt-asf commented on websocket/2.2/_index.md
> +
Fixed.

2023-06-16 12:57 UTC, kazumura commented
@markt-asf   
Thanks for update.  
But a preview page creation was failed.  
I 'm not sure the reason, but one thing I noticed is you have not created the release page yet.
"https://projects.eclipse.org/projects/ee4j.websocket/releases/2.2"  
So please create the release page and rerun preview page creation.

2023-06-19 14:47 UTC, markt-asf commented
@kazumura Release page created. I don't have karma to rerun preview page creation.

2023-06-21 02:41 UTC, kazumura commented
Not only this PR, but any commits since last week fail to create preview pages.

2023-07-04 00:14 UTC, kazumura approved these changes

2023-07-12 05:08 UTC, kazumura commented
Ballot passed.
https://www.eclipse.org/lists/jakarta.ee-spec/msg03011.html

2023-07-12 05:09 UTC, merged