Jakarta Annotations 3.0
jakartaee/specifications pull request #699
Opened 2024-02-17 17:22 UTC by lukasj

## Specification PR template
When creating a specification project release review, create PRs with the content defined as follows.

Include the following in the PR:
- [x] A directory in the form wombat/x.y where x.y is the release major.minor version, and the directory contains the following.
- [x] Specification PDF in the form of jakarta-wombat-spec-x.y.pdf
- [x] Specification HTML in the form of jakarta-wombat-spec-x.y.html
- [x] A specification page named _index.md following the template at:
      https://github.com/jakartaee/specification-committee/blob/master/spec_page_template.md
- [ ] For a Progress Review, that sufficient progress has been made on a Compatible Implementation and TCK, to ensure that the spec is implementable and testable.
- [ ] For a [Release Review](https://www.eclipse.org/projects/handbook/#release-review), a summary that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification. The TCK users guide MUST include the instructions to run the compatible implementations used to validate the release.
Instructions MAY be by reference.
   - [ ] Updated release record
   - [ ] Generated IP Log
   - [ ] Email to PMC
   - [ ] Start release review by emailing EMO 
- [x] The URL of the OSSRH staging repository for the api, javadoc:
      https://jakarta.oss.sonatype.org/content/repositories/jakartaannotation-1014/
- [ ] The URL of the staging directory on downloads.eclipse.org for the proposed EFTL TCK binary:
      https://www.eclipse.org/downloads/download.php?file=/ee4j/jakartaee-tck/jakartaee11/staged/eftl/jakarta-annotations-tck-3.0.0.zip
- [ ] The URL of the compatibility certification request issue:
      <add URL here>
- [x] Specification JavaDoc in the wombat/x.y/apidocs directory. 
If desired, an optional second PR can be created to contain just the JavaDoc in the `apidocs` directory.

Note: If any item does not apply, check it and mark N/A below it.

2024-02-29 23:28 UTC, lukasj commented
TCK is ready

2024-03-04 12:56 UTC, ivargrimstad requested changes
Remove " (Under development)" from the title

Reword the summary to past tense. E.g.

Change 

"The purpose of this release is to fully remove the deprecated @ManagedBean annotation."

to 

"This release fully removes the deprecated @ManagedBean annotation."

2024-03-04 15:48 UTC, ivargrimstad commented
@lukasj  Arjan said that GlassFish is planning a 8.0.0-M3 this week that may be used for the CCR for this PR since it incorporates Annotations 3.0

2024-03-04 15:55 UTC, lukasj commented
@ivargrimstad comments applied; let me know once M3 is ready

2024-03-22 11:00 UTC, lukasj commented
done

2024-03-22 13:22 UTC, ivargrimstad commented on annotations/3.0/_index.md
> +TBD
Add GlassFish 8.0.0-M3 here

2024-03-22 13:48 UTC, lukasj commented on annotations/3.0/_index.md
> +TBD
done

2024-03-22 15:14 UTC, ivargrimstad approved these changes

2024-03-25 14:19 UTC, ivargrimstad commented
@lukasj  I just talked to @arjantijms . It should be possible to run the TCK with Java 17 and GlassFish 8.0.0-M3 since GlassFish isn't started by the TCK run. Arjan is 95% sure about this.

2024-03-26 14:31 UTC, lukasj commented
> @lukasj I just talked to @arjantijms . It should be possible to run the TCK with Java 17 and GlassFish 8.0.0-M3 since GlassFish isn't started by the TCK run. Arjan is 95% sure about this.

the fact it is possible does not mean it is the right way to proceed as it shows reliance on the TCK implementation details, I mean what is the point of certifying a runtime known to NOT support SE 17? But it is the most simple way forward, so done...

2024-04-07 06:11 UTC, merged

2024-04-07 06:15 UTC, ivargrimstad commented
* On ballot completion, the specification committee mentor:
 - [ ] adds this final checklist to the main PR.
 - [ ] adds the `approved` label to the PRs, and sends out the Ballot Summary per this [template](#ballot-summary-email-template) to the [public Jakarta EE Specification Committee email list](jakarta.ee-spec@eclipse.org)
 - [ ] calculates the staged EFTL TCK signature and promotes it to the committee download area
  using the https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/ job. Manually editing the jenkins Build Information will help identify the build (ie. Mail 2.0 or CDI 3.0).
 - [ ] merges the specification (and apidocs) PRs, ensuring the "date:" field in the _index.md file has an appropriate value to allow publishing.
 - [ ] updates the specification page with the ballot results. This is normally done via a separate PR that should be reviewed, approved, and merged.
 - [ ] notifies the EMO of the ballot results by email to [emo@eclipse-foundation.org](emo@eclipse-foundation.org). Just forward the ballot summary note sent earlier to the public Spec Committee email list.
 - [ ] creates an issue in the specification project that includes the following checklist for the specification project team: https://github.com/jakartaee/common-annotations-api/issues/139